In [1]:
import numpy as np

In [2]:
x = [1,1,3,5]

In [3]:
print (type(x))

<class 'list'>


In [4]:
n = np.array(x)

In [5]:
n

array([1, 1, 3, 5])

In [6]:
print (type(n))

<class 'numpy.ndarray'>


In [7]:
print (n)

[1 1 3 5]


In [8]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [9]:
print (m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print (type (m))

<class 'numpy.ndarray'>


In [11]:
print (m.shape)

(3, 3)


In [12]:
m.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
np.linalg.det(m)

-9.51619735392994e-16

In [14]:
np.linalg.inv(m)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])